security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login       
                check_path: app_login       
                default_target_path: page_hello  
                enable_csrf: true
            logout:
                path: app_logout           
            custom_authenticator: App\Security\AppAuthenticator
            entry_point: form_login        
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800           
                path: /

    role_hierarchy:
        ROLE_BANNED: []                  
        ROLE_USER: [ROLE_BANNED]         
        ROLE_ADMIN: [ROLE_USER] 

    access_control:
        - { path: ^/banned, roles: ROLE_BANNED }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY, allow_if: "not is_granted('ROLE_BANNED')" }

        - { path: ^/profile, roles: ROLE_USER }

        - { path: ^/admin, roles: ROLE_ADMIN }
